name: ingogo
description: Ingogo Flutter challenge app
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  socket_io_client: ^2.0.1
  http: ^0.13.5
  google_fonts: ^4.0.3
  flutter_native_splash: ^2.2.16
  another_flushbar: ^1.12.29
  flutter_html: 3.0.0-alpha.6
  mockito: ^5.3.2
  web_socket_channel: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/